networks:
  heygem_network:
    driver: bridge

services:
  # HeyGem Web 應用 (整合後的前後端)
  heygem-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heygem-web
    # 移除外部端口暴露，只通過 nginx 代理訪問
    expose:
      - "5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - TTS_URL=http://tts-server:18180
      - MY_TTS_URL=http://heygem-tts-services:8080
      - ASR_URL=http://asr-server:10095
    volumes:
      # 一次性掛載整個專案目錄
      - .:/app
      # 保留 node_modules volume 避免權限問題
      - node_modules:/app/node_modules
    networks:
      - heygem_network
    depends_on:
      - tts-server
      - heygem-tts-services
    restart: unless-stopped

  # TTS 語音合成服務 (Fish Speech - 使用現有鏡像)
  tts-server:
    image: guiji2025/fish-speech-ziming
    container_name: heygem-tts
    restart: unless-stopped
    ports:
      - "18180:8080"
    # 移除過時的 voice 目錄掛載
    command: /bin/bash -c "/opt/conda/envs/python310/bin/python3 tools/api_server.py --listen 0.0.0.0:8080"
    networks:
      - heygem_network

  # HeyGem 自定義 TTS 服務集合
  heygem-tts-services:
    build:
      context: ./tts-services
      dockerfile: Dockerfile
    container_name: heygem-tts-services
    ports:
      - "18200:8080"  # 主入口
      - "18201:8081"  # TTS 服務 1
      - "18202:8082"  # TTS 服務 2
      - "18203:8083"  # TTS 服務 3
    environment:
      - PYTHONPATH=/app
      # MiniMax TTS API 設定
      - MINIMAX_API_KEY=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJHcm91cE5hbWUiOiJNSVMgUkQiLCJVc2VyTmFtZSI6Ik1JUyBSRCIsIkFjY291bnQiOiIiLCJTdWJqZWN0SUQiOiIxOTMwODQzMjQ3ODg2NzMzODg4IiwiUGhvbmUiOiIiLCJHcm91cElEIjoiMTkzMDg0MzI0Nzg4MjUzOTU4NCIsIlBhZ2VOYW1lIjoiIiwiTWFpbCI6Im1pc0BhaWNyZWF0ZTM2MC5jb20iLCJDcmVhdGVUaW1lIjoiMjAyNS0wNi0wNiAxNToxMDoyNyIsIlRva2VuVHlwZSI6MSwiaXNzIjoibWluaW1heCJ9.dPZgibBPgTtJ2D-vIY8IxlNTqOknAYsEnYtq0XaxsEUpt_8gkUOmOQZ0463kXz4JmGAY39ympUBgAXQSrg-TG00BiZHqKqnFr54Xmhr3Fi0WlFJqZBPnzIu6SPJc3TbHc9lXSd_Y68ov758Rs6MVgKYxy_u40MoJOQoP-aS-9RiiiV8LWOlR38Hw74ZZhV3rAHYXKRYPPS1IECaT8dpBMjlKzn4__-Zk7GPUn4Qfz7uG3ly1fw_dYrJZtWHFqWg3Zt5V04R4ky6jrIP3dGL3Kd5kO78eYiYXwmZGfFF6kTsdlhYqYARMbt-6gDQVxmX906hEO4OVUcZAtp4pz7eyCA
      - MINIMAX_GROUP_ID=1930843247882539584
      - MINIMAX_BASE_URL=https://api.minimaxi.chat/v1/t2a_v2
      - MINIMAX_MODEL=speech-02-turbo
      # ATEN AIVoice TTS API 設定
      - EUGENES_API_TOKEN=8ecd2f02836f456abf693163c8077965
      - EUGENES_BASE_URL=https://www.aivoice.com.tw/business/enterprise
      # 其他設定
      - DEBUG=true
      - LOG_LEVEL=INFO
    volumes:
      # 一次性掛載 TTS 服務目錄
      - ./tts-services:/app
      - ./data:/app/data
    networks:
      - heygem_network
    restart: unless-stopped

  # ASR 語音識別服務
  asr-server:
    image: guiji2025/fun-asr
    container_name: heygem-asr
    restart: unless-stopped
    runtime: nvidia
    privileged: true
    working_dir: /workspace/FunASR/runtime
    ports:
      - "10095:10095"
    command: sh /run.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # 移除過時的 voice 目錄掛載
    networks:
      - heygem_network

  # 數字人生成服務 (Face2Face)
  heygem-gen-video:
    image: guiji2025/heygem.ai
    container_name: heygem-gen-video
    restart: unless-stopped
    runtime: nvidia
    privileged: true
    ports:
      - "8383:8383"
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    volumes:
      - ./data:/code/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    shm_size: '8g'
    command: python /code/app_local.py
    networks:
      - heygem_network

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: heygem-nginx
    ports:
      - "80:80"
      - "8883:8883"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - heygem_network
    depends_on:
      - heygem-web
      - tts-server
      - heygem-tts-services
      - asr-server
      - heygem-gen-video
    restart: unless-stopped

volumes:
  node_modules:
